runtime: nodejs18
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  - REACT_APP_BACK_END_URL: 'https://back-end-ufb75eeywa-uk.a.run.app'
